
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: issuer
    namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-issuer
  namespace: istio-system
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificates", "certificaterequests"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-issuer-binding
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: issuer
  namespace: istio-system
roleRef:
  kind: Role
  name: cert-manager-issuer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issuer
  namespace: istio-system
---
apiVersion: v1
kind: Secret
metadata:
  name: issuer-token
  namespace: istio-system
  annotations:
    kubernetes.io/service-account.name: issuer
type: kubernetes.io/service-account-token

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-intermediate-issuer
  namespace: istio-system
spec:
  vault:
    path: pki/root/sign-intermediate
    server: http://vault.vault.svc.cluster.local:8200
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          name: issuer-token
          key: token

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: istio-system
spec:
  secretName: istio-ca
  duration: 7200h
  renewBefore: 3600h
  subject:
    organizations:
      - cluster.local
      - cert-manager
      - kubernetes.default.svc
  commonName: istio-ca
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: istio-intermediate-issuer
    kind: Issuer
    group: cert-manager.io
  # usages:
  #   - digital signature
  #   - key encipherment
  #   - cert sign
  #   - client auth
  #   - server auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-ca
  namespace: istio-system
spec:
  ca:
    secretName: istio-ca


