---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: istio-system
spec:
  secretName: istio-ca
  duration: 720h
  renewBefore: 360h
  subject:
    organizations:
      - cluster.local
      - cert-manager
      - kubernetes.default.svc
  commonName: istio-ca
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io
